export const translations: Record<string, string> = {
    'Activate the hand tool': 'Активувати інструмент "Рука"',
    'Activate the lasso tool': 'Активувати ласо',
    'Activate the create/remove space tool': 'Активувати інструмент "Простір"',
    'Create new space tool': 'Створити простір',
    'Activate the global connect tool': 'Активувати інструмент з\'єднання',
    'Create StartEvent': 'Створити початкову подію',
    'Create start event': 'Створити початкову подію',
    'Create Intermediate/Boundary Event': 'Створити проміжну подію',
    'Create intermediate/boundary event': 'Створити проміжну подію',
    'Create EndEvent': 'Створити кінцеву подію',
    'Create end event': 'Створити кінцеву подію',
    'Create Gateway': 'Створити шлюз',
    'Create gateway': 'Створити шлюз',
    'Create Task': 'Створити завдання',
    'Create task': 'Створити завдання',
    'Create DataObjectReference': 'Створити об\'єкт даних',
    'Create data object reference': 'Створити об\'єкт даних',
    'Create DataStoreReference': 'Створити сховище даних',
    'Create data store reference': 'Створити сховище даних',
    'Create Expansion of SubProcess': 'Розгорнути підпроцес',
    'Create expanded sub-process': 'Розгорнути підпроцес',
    'Create Pool/Participant': 'Створити Пул/Учасника',
    'Create pool/participant': 'Створити Пул/Учасника',
    'Create Group': 'Створити групу',
    'Create group': 'Створити групу',
    'Append Task': 'Додати завдання',
    'Append task': 'Додати завдання',
    'Append EndEvent': 'Додати кінцеву подію',
    'Append end event': 'Додати кінцеву подію',
    'Append Gateway': 'Додати шлюз',
    'Append gateway': 'Додати шлюз',
    'Append Intermediate/Boundary Event': 'Додати проміжну подію',
    'Append intermediate/boundary event': 'Додати проміжну подію',
    'Remove': 'Видалити',
    'Connect': 'З\'єднати',
    'Connect using Sequence/MessageFlow or Association': 'З\'єднати',
    'Change type': 'Змінити тип',
    'Add Lane above': 'Додати доріжку зверху',
    'Add lane above': 'Додати доріжку зверху',
    'Divide into two Lanes': 'Розділити на дві доріжки',
    'Divide into two lanes': 'Розділити на дві доріжки',
    'Add Lane below': 'Додати доріжку знизу',
    'Add lane below': 'Додати доріжку знизу',
    'Loop': 'Цикл',
    'Ad-hoc': 'Ad-hoc',
    'Parallel Multi Instance': 'Паралельне виконання',
    'Sequential Multi Instance': 'Послідовне виконання',
    'Task': 'Завдання',
    'Send Task': 'Завдання відправки',
    'Receive Task': 'Завдання отримання',
    'User Task': 'Завдання користувача',
    'Manual Task': 'Ручне завдання',
    'Business Rule Task': 'Бізнес-правило',
    'Service Task': 'Сервісне завдання',
    'Script Task': 'Скрипт',
    'Call Activity': 'Виклик активності',
    'Sub Process (collapsed)': 'Підпроцес (згорнутий)',
    'Sub Process (expanded)': 'Підпроцес (розгорнутий)',
    'Exclusive Gateway': 'Ексклюзивний шлюз',
    'Parallel Gateway': 'Паралельний шлюз',
    'Inclusive Gateway': 'Інклюзивний шлюз',
    'Complex Gateway': 'Комплексний шлюз',
    'Event based Gateway': 'Шлюз на основі подій',
    'Message Start Event': 'Подія початку повідомлення',
    'Timer Start Event': 'Подія початку таймера',
    'Conditional Start Event': 'Подія початку умови',
    'Signal Start Event': 'Подія початку сигналу',
    'Error Start Event': 'Подія початку помилки',
    'Escalation Start Event': 'Подія початку ескалації',
    'Compensation Start Event': 'Подія початку компенсації',
    'Message Start Event (non-interrupting)': 'Подія початку повідомлення (не перериває)',
    'Timer Start Event (non-interrupting)': 'Подія початку таймера (не перериває)',
    'Conditional Start Event (non-interrupting)': 'Подія початку умови (не перериває)',
    'Signal Start Event (non-interrupting)': 'Подія початку сигналу (не перериває)',
    'Escalation Start Event (non-interrupting)': 'Подія початку ескалації (не перериває)',
    'Message Intermediate Catch Event': 'Проміжна подія перехоплення повідомлення',
    'Message Intermediate Throw Event': 'Проміжна подія кидання повідомлення',
    'Timer Intermediate Catch Event': 'Проміжна подія перехоплення таймера',
    'Escalation Intermediate Throw Event': 'Проміжна подія кидання ескалації',
    'Conditional Intermediate Catch Event': 'Проміжна подія перехоплення умови',
    'Link Intermediate Catch Event': 'Проміжна подія перехоплення посилання',
    'Link Intermediate Throw Event': 'Проміжна подія кидання посилання',
    'Compensation Intermediate Throw Event': 'Проміжна подія кидання компенсації',
    'Signal Intermediate Catch Event': 'Проміжна подія перехоплення сигналу',
    'Signal Intermediate Throw Event': 'Проміжна подія кидання сигналу',
    'Message End Event': 'Кінцева подія повідомлення',
    'Escalation End Event': 'Кінцева подія ескалації',
    'Error End Event': 'Кінцева подія помилки',
    'Cancel End Event': 'Кінцева подія скасування',
    'Compensation End Event': 'Кінцева подія компенсації',
    'Signal End Event': 'Кінцева подія сигналу',
    'Terminate End Event': 'Кінцева подія термінації',
    'Sequence Flow': 'Потік управління',
    'Default Flow': 'Потік за замовчуванням',
    'Conditional Flow': 'Умовний потік',
    'Association': 'Асоціація',
    'Data Object Reference': 'Посилання на об\'єкт даних',
    'Data Store Reference': 'Посилання на сховище даних',
    'Text Annotation': 'Текстова анотація',
    // Replace Menu (Change Element)
    'Change element': 'Змінити елемент',
    'Start event': 'Початкова подія',
    'Intermediate throw event': 'Проміжна подія (кидання)',
    'End event': 'Кінцева подія',
    'Message intermediate catch event': 'Проміжна подія отримання повідомлення',
    'Message intermediate throw event': 'Проміжна подія відправки повідомлення',
    'Timer intermediate catch event': 'Проміжна подія таймера',
    'Escalation intermediate throw event': 'Проміжна подія ескалації',
    'Conditional intermediate catch event': 'Проміжна подія умови',
    'Link intermediate catch event': 'Проміжна подія посилання (вхід)',
    'Link intermediate throw event': 'Проміжна подія посилання (вихід)',
    'Compensation intermediate throw event': 'Проміжна подія компенсації',
    'Signal intermediate catch event': 'Проміжна подія отримання сигналу',
    'Signal intermediate throw event': 'Проміжна подія відправки сигналу',
    'Message end event': 'Кінцева подія повідомлення',
    'Escalation end event': 'Кінцева подія ескалації',
    'Error end event': 'Кінцева подія помилки',
    'Cancel end event': 'Кінцева подія скасування',
    'Compensation end event': 'Кінцева подія компенсації',
    'Signal end event': 'Кінцева подія сигналу',
    'Terminate end event': 'Кінцева подія термінації',
    'Parallel gateway': 'Паралельний шлюз',
    'Exclusive gateway': 'Ексклюзивний шлюз',
    'Inclusive gateway': 'Інклюзивний шлюз',
    'Complex gateway': 'Комплексний шлюз',
    'Event based gateway': 'Шлюз на основі подій',
    'Connect using DataInputAssociation': 'З\'єднати (вхідні дані)',
    'Connect using DataOutputAssociation': 'З\'єднати (вихідні дані)',
    'Empty': 'Пусто',
    'Collection': 'Колекція',
    // Task Types (Sentence case for Replace Menu)
    'User task': 'Завдання користувача',
    'Service task': 'Сервісне завдання',
    'Send task': 'Завдання відправки',
    'Receive task': 'Завдання отримання',
    'Manual task': 'Ручне завдання',
    'Business rule task': 'Бізнес-правило',
    'Script task': 'Скрипт',
    'Call activity': 'Виклик активності',
    'Sub-process (collapsed)': 'Підпроцес (згорнутий)',
    'Sub-process (expanded)': 'Підпроцес (розгорнутий)',
    'Transaction': 'Транзакція',
    'Event sub-process': 'Підпроцес події'
};

export function customTranslate(template: string, replacements: Record<string, string>) {
    replacements = replacements || {};

    // Translate
    const translation = translations[template] || template;

    // Replace
    return translation.replace(/{([^}]+)}/g, function (_, key) {
        return replacements[key] || '{' + key + '}';
    });
}
